# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [leejun]
  pull_request:
    branches: [leejun]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Npm -v
        run: npm -v

      - name: create env file

        working-directory: ./

        run: |
          pwd
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo MONGODB=${{ secrets.MONGODB }} >> .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID}} >> .env
          echo AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME}} >> .env
          echo AWS_REGION=${{ secrets.AWS_REGION}} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}} >> .env
          echo DB_END_POINT=${{ secrets.DB_END_POINT}} >> .env
          echo DB_NAME=${{ secrets.DB_NAME}} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD}} >> .env
          echo DB_PORT=${{ secrets.DB_PORT}} >> .env
          echo DB_USER=${{ secrets.DB_USER}} >> .env
          echo REDIS_HOST=${{ secrets.REDIS_HOST}} >> .env
          echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD}} >> .env
          echo REDIS_PORT=${{ secrets.REDIS_PORT}} >> .env
          echo REDIS_USERNAME=${{ secrets.REDIS_USERNAME}} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY}} >> .env

          cat .env

      - name: build server files
        working-directory: ./
        run: |
          npm install
          npm npm run build
